//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeeScore.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeeScore.Translations.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc golf.
        /// </summary>
        internal static string GameType_DiskGolf {
            get {
                return ResourceManager.GetString("GameType_DiskGolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmers golf.
        /// </summary>
        internal static string GameType_FarmersGolf {
            get {
                return ResourceManager.GetString("GameType_FarmersGolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot golf.
        /// </summary>
        internal static string GameType_FootGolf {
            get {
                return ResourceManager.GetString("GameType_FootGolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golf.
        /// </summary>
        internal static string GameType_Golf {
            get {
                return ResourceManager.GetString("GameType_Golf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midget golf.
        /// </summary>
        internal static string GameType_MidgetGolf {
            get {
                return ResourceManager.GetString("GameType_MidgetGolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short golf.
        /// </summary>
        internal static string GameType_ShortGolf {
            get {
                return ResourceManager.GetString("GameType_ShortGolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By invitation number.
        /// </summary>
        internal static string PlayerSelection_ByInvitationNumber {
            get {
                return ResourceManager.GetString("PlayerSelection_ByInvitationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By NFC.
        /// </summary>
        internal static string PlayerSelection_ByNfc {
            get {
                return ResourceManager.GetString("PlayerSelection_ByNfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string PlayerSelection_Manual {
            get {
                return ResourceManager.GetString("PlayerSelection_Manual", resourceCulture);
            }
        }
    }
}
