//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeeScore.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeeScore.Translations.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        internal static string btn_back {
            get {
                return ResourceManager.GetString("btn_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string btn_join {
            get {
                return ResourceManager.GetString("btn_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        internal static string btn_next {
            get {
                return ResourceManager.GetString("btn_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string btn_no {
            get {
                return ResourceManager.GetString("btn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btn_OK {
            get {
                return ResourceManager.GetString("btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string btn_start {
            get {
                return ResourceManager.GetString("btn_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string btn_yes {
            get {
                return ResourceManager.GetString("btn_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc golf.
        /// </summary>
        internal static string GameType_DiskGolf {
            get {
                return ResourceManager.GetString("GameType_DiskGolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmers golf.
        /// </summary>
        internal static string GameType_FarmersGolf {
            get {
                return ResourceManager.GetString("GameType_FarmersGolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot golf.
        /// </summary>
        internal static string GameType_FootGolf {
            get {
                return ResourceManager.GetString("GameType_FootGolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golf.
        /// </summary>
        internal static string GameType_Golf {
            get {
                return ResourceManager.GetString("GameType_Golf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midget golf.
        /// </summary>
        internal static string GameType_MidgetGolf {
            get {
                return ResourceManager.GetString("GameType_MidgetGolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short golf.
        /// </summary>
        internal static string GameType_ShortGolf {
            get {
                return ResourceManager.GetString("GameType_ShortGolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation.
        /// </summary>
        internal static string lbl_abbreviation {
            get {
                return ResourceManager.GetString("lbl_abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose or add venue.
        /// </summary>
        internal static string lbl_choose_or_add_venue {
            get {
                return ResourceManager.GetString("lbl_choose_or_add_venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current player.
        /// </summary>
        internal static string lbl_current_player {
            get {
                return ResourceManager.GetString("lbl_current_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tee.
        /// </summary>
        internal static string lbl_current_tee {
            get {
                return ResourceManager.GetString("lbl_current_tee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the game number and press Join.
        /// </summary>
        internal static string lbl_fill_invitation_number {
            get {
                return ResourceManager.GetString("lbl_fill_invitation_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find or add players.
        /// </summary>
        internal static string lbl_find_or_add_players {
            get {
                return ResourceManager.GetString("lbl_find_or_add_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass this number to the other players. They can enter this number at the &apos;Join Game&apos; page..
        /// </summary>
        internal static string lbl_game_number {
            get {
                return ResourceManager.GetString("lbl_game_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game type.
        /// </summary>
        internal static string lbl_game_type {
            get {
                return ResourceManager.GetString("lbl_game_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining:.
        /// </summary>
        internal static string lbl_joining {
            get {
                return ResourceManager.GetString("lbl_joining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string lbl_location {
            get {
                return ResourceManager.GetString("lbl_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_name {
            get {
                return ResourceManager.GetString("lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. of players.
        /// </summary>
        internal static string lbl_players_count {
            get {
                return ResourceManager.GetString("lbl_players_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select other players.
        /// </summary>
        internal static string lbl_select_other_players {
            get {
                return ResourceManager.GetString("lbl_select_other_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start tee.
        /// </summary>
        internal static string lbl_start_tee {
            get {
                return ResourceManager.GetString("lbl_start_tee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started at.
        /// </summary>
        internal static string lbl_started {
            get {
                return ResourceManager.GetString("lbl_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all game data ....
        /// </summary>
        internal static string lbl_starting_getting_data {
            get {
                return ResourceManager.GetString("lbl_starting_getting_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving game ....
        /// </summary>
        internal static string lbl_starting_saving_data {
            get {
                return ResourceManager.GetString("lbl_starting_saving_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting game ....
        /// </summary>
        internal static string lbl_starting_starting {
            get {
                return ResourceManager.GetString("lbl_starting_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tee.
        /// </summary>
        internal static string lbl_tee {
            get {
                return ResourceManager.GetString("lbl_tee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. of tees.
        /// </summary>
        internal static string lbl_tees_count {
            get {
                return ResourceManager.GetString("lbl_tees_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        internal static string lbl_venue {
            get {
                return ResourceManager.GetString("lbl_venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By invitation number.
        /// </summary>
        internal static string PlayerSelection_ByInvitationNumber {
            get {
                return ResourceManager.GetString("PlayerSelection_ByInvitationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By NFC.
        /// </summary>
        internal static string PlayerSelection_ByNfc {
            get {
                return ResourceManager.GetString("PlayerSelection_ByNfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By QR Code.
        /// </summary>
        internal static string PlayerSelection_ByQrCode {
            get {
                return ResourceManager.GetString("PlayerSelection_ByQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string PlayerSelection_Manual {
            get {
                return ResourceManager.GetString("PlayerSelection_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join game.
        /// </summary>
        internal static string title_join_game {
            get {
                return ResourceManager.GetString("title_join_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string title_new_game {
            get {
                return ResourceManager.GetString("title_new_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game player.
        /// </summary>
        internal static string title_new_game_player {
            get {
                return ResourceManager.GetString("title_new_game_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New venue.
        /// </summary>
        internal static string title_new_venue {
            get {
                return ResourceManager.GetString("title_new_venue", resourceCulture);
            }
        }
    }
}
